 [env:crowpanel_21]
platform  = espressif32 @ 6.6.0
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
upload_port   = COM20
upload_resetmethod = no_reset

board_build.arduino.memory_type = qio_opi
board_build.flash_mode          = qio
board_build.psram_type          = opi
board_build.partitions          = partitions/partitions_16mb.csv
board_build.filesystem          = littlefs

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DCORE_DEBUG_LEVEL=3
    -I"${PROJECT_DIR}/src"
    -I"${PROJECT_DIR}/include"

lib_deps =
    moononournation/GFX Library for Arduino @ 1.4.7
    lvgl/lvgl @ ^9.2.0
    tzapu/WiFiManager @ ^2.0.17
    knolleary/PubSubClient @ ^2.8
    terrorsl/sMQTTBroker
    bblanchon/ArduinoJson @ ^7.0.0
